name: Running Novel Tracking Workflows

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

permissions:
  contents: write
    
jobs:
    status_update:
      name: Update Novel Status
      uses: ./.github/workflows/novel-status.yml

    check_novel_update:
      name: Check Novel Update
      uses: ./.github/workflows/check-new-chapters.yml